name: scp files

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Copy file via SSH
    runs-on: ubuntu-latest
    steps:
      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 4.236.144.47
          username: vivek
          password: Password@123
          port: 22
          timeout: 1000s
          source: ./*
          target: /var/www/html/

      - name: SSH into the server
        uses: appleboy/ssh-action@v0.4.0
        with:
          host: 4.236.144.47
          username: vivek
          password: Password@123
          port: 22
          script: |
            cd /var/www/html
            git pull origin main
